/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutPublicRouteImport } from './routes/_layout-public'
import { Route as LayoutPrivateRouteImport } from './routes/_layout-private'

const LayoutPublicIndexLazyRouteImport = createFileRoute('/_layout-public/')()
const LayoutPublicSignupLazyRouteImport = createFileRoute(
  '/_layout-public/signup',
)()
const LayoutPublicLoginLazyRouteImport = createFileRoute(
  '/_layout-public/login',
)()
const LayoutPrivateDashboardLazyRouteImport = createFileRoute(
  '/_layout-private/dashboard',
)()

const LayoutPublicRoute = LayoutPublicRouteImport.update({
  id: '/_layout-public',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPrivateRoute = LayoutPrivateRouteImport.update({
  id: '/_layout-private',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicIndexLazyRoute = LayoutPublicIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPublicRoute,
} as any).lazy(() =>
  import('./routes/_layout-public/index.lazy').then((d) => d.Route),
)
const LayoutPublicSignupLazyRoute = LayoutPublicSignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LayoutPublicRoute,
} as any).lazy(() =>
  import('./routes/_layout-public/signup.lazy').then((d) => d.Route),
)
const LayoutPublicLoginLazyRoute = LayoutPublicLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutPublicRoute,
} as any).lazy(() =>
  import('./routes/_layout-public/login.lazy').then((d) => d.Route),
)
const LayoutPrivateDashboardLazyRoute =
  LayoutPrivateDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutPrivateRoute,
  } as any).lazy(() =>
    import('./routes/_layout-private/dashboard.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof LayoutPublicIndexLazyRoute
  '/dashboard': typeof LayoutPrivateDashboardLazyRoute
  '/login': typeof LayoutPublicLoginLazyRoute
  '/signup': typeof LayoutPublicSignupLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutPublicIndexLazyRoute
  '/dashboard': typeof LayoutPrivateDashboardLazyRoute
  '/login': typeof LayoutPublicLoginLazyRoute
  '/signup': typeof LayoutPublicSignupLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout-private': typeof LayoutPrivateRouteWithChildren
  '/_layout-public': typeof LayoutPublicRouteWithChildren
  '/_layout-private/dashboard': typeof LayoutPrivateDashboardLazyRoute
  '/_layout-public/login': typeof LayoutPublicLoginLazyRoute
  '/_layout-public/signup': typeof LayoutPublicSignupLazyRoute
  '/_layout-public/': typeof LayoutPublicIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/signup'
  id:
    | '__root__'
    | '/_layout-private'
    | '/_layout-public'
    | '/_layout-private/dashboard'
    | '/_layout-public/login'
    | '/_layout-public/signup'
    | '/_layout-public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutPrivateRoute: typeof LayoutPrivateRouteWithChildren
  LayoutPublicRoute: typeof LayoutPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout-public': {
      id: '/_layout-public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-private': {
      id: '/_layout-private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-public/': {
      id: '/_layout-public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicIndexLazyRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout-public/signup': {
      id: '/_layout-public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutPublicSignupLazyRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout-public/login': {
      id: '/_layout-public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutPublicLoginLazyRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout-private/dashboard': {
      id: '/_layout-private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutPrivateDashboardLazyRouteImport
      parentRoute: typeof LayoutPrivateRoute
    }
  }
}

interface LayoutPrivateRouteChildren {
  LayoutPrivateDashboardLazyRoute: typeof LayoutPrivateDashboardLazyRoute
}

const LayoutPrivateRouteChildren: LayoutPrivateRouteChildren = {
  LayoutPrivateDashboardLazyRoute: LayoutPrivateDashboardLazyRoute,
}

const LayoutPrivateRouteWithChildren = LayoutPrivateRoute._addFileChildren(
  LayoutPrivateRouteChildren,
)

interface LayoutPublicRouteChildren {
  LayoutPublicLoginLazyRoute: typeof LayoutPublicLoginLazyRoute
  LayoutPublicSignupLazyRoute: typeof LayoutPublicSignupLazyRoute
  LayoutPublicIndexLazyRoute: typeof LayoutPublicIndexLazyRoute
}

const LayoutPublicRouteChildren: LayoutPublicRouteChildren = {
  LayoutPublicLoginLazyRoute: LayoutPublicLoginLazyRoute,
  LayoutPublicSignupLazyRoute: LayoutPublicSignupLazyRoute,
  LayoutPublicIndexLazyRoute: LayoutPublicIndexLazyRoute,
}

const LayoutPublicRouteWithChildren = LayoutPublicRoute._addFileChildren(
  LayoutPublicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutPrivateRoute: LayoutPrivateRouteWithChildren,
  LayoutPublicRoute: LayoutPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
