/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutPublicImport } from './routes/_layout-public'
import { Route as LayoutPrivateImport } from './routes/_layout-private'

// Create Virtual Routes

const LayoutPublicIndexLazyImport = createFileRoute('/_layout-public/')()
const LayoutPublicSignupLazyImport = createFileRoute('/_layout-public/signup')()
const LayoutPublicLoginLazyImport = createFileRoute('/_layout-public/login')()
const LayoutPrivateDashboardLazyImport = createFileRoute(
  '/_layout-private/dashboard',
)()

// Create/Update Routes

const LayoutPublicRoute = LayoutPublicImport.update({
  id: '/_layout-public',
  getParentRoute: () => rootRoute,
} as any)

const LayoutPrivateRoute = LayoutPrivateImport.update({
  id: '/_layout-private',
  getParentRoute: () => rootRoute,
} as any)

const LayoutPublicIndexLazyRoute = LayoutPublicIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutPublicRoute,
} as any).lazy(() =>
  import('./routes/_layout-public/index.lazy').then((d) => d.Route),
)

const LayoutPublicSignupLazyRoute = LayoutPublicSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => LayoutPublicRoute,
} as any).lazy(() =>
  import('./routes/_layout-public/signup.lazy').then((d) => d.Route),
)

const LayoutPublicLoginLazyRoute = LayoutPublicLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => LayoutPublicRoute,
} as any).lazy(() =>
  import('./routes/_layout-public/login.lazy').then((d) => d.Route),
)

const LayoutPrivateDashboardLazyRoute = LayoutPrivateDashboardLazyImport.update(
  {
    path: '/dashboard',
    getParentRoute: () => LayoutPrivateRoute,
  } as any,
).lazy(() =>
  import('./routes/_layout-private/dashboard.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout-private': {
      preLoaderRoute: typeof LayoutPrivateImport
      parentRoute: typeof rootRoute
    }
    '/_layout-public': {
      preLoaderRoute: typeof LayoutPublicImport
      parentRoute: typeof rootRoute
    }
    '/_layout-private/dashboard': {
      preLoaderRoute: typeof LayoutPrivateDashboardLazyImport
      parentRoute: typeof LayoutPrivateImport
    }
    '/_layout-public/login': {
      preLoaderRoute: typeof LayoutPublicLoginLazyImport
      parentRoute: typeof LayoutPublicImport
    }
    '/_layout-public/signup': {
      preLoaderRoute: typeof LayoutPublicSignupLazyImport
      parentRoute: typeof LayoutPublicImport
    }
    '/_layout-public/': {
      preLoaderRoute: typeof LayoutPublicIndexLazyImport
      parentRoute: typeof LayoutPublicImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutPrivateRoute.addChildren([LayoutPrivateDashboardLazyRoute]),
  LayoutPublicRoute.addChildren([
    LayoutPublicLoginLazyRoute,
    LayoutPublicSignupLazyRoute,
    LayoutPublicIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
